package tub.iosp.budcloand.framework.control.database;

import java.util.ArrayList;
import java.util.List;

import tub.iosp.budcloand.framework.model.CacheTimeFrame;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;

// TODO: Auto-generated Javadoc
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CACHE_TIME_FRAME.
*/
public class CacheTimeFrameDao extends AbstractDao<CacheTimeFrame, Long> {

    /** The Constant TABLENAME. */
    public static final String TABLENAME = "CACHE_TIME_FRAME";

    /**
     * Properties of entity CacheTimeFrame.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        
        /** The Constant Id. */
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        
        /** The Constant Last. */
        public final static Property Last = new Property(1, java.util.Date.class, "last", false, "LAST");
        
        /** The Constant First. */
        public final static Property First = new Property(2, java.util.Date.class, "first", false, "FIRST");
        
        /** The Constant NextFrame. */
        public final static Property NextFrame = new Property(3, Long.class, "nextFrame", false, "NEXT_FRAME");
    };

    /** The dao session. */
    private DaoSession daoSession;


    /**
     * Instantiates a new cache time frame dao.
     *
     * @param config the config
     */
    public CacheTimeFrameDao(DaoConfig config) {
        super(config);
    }
    
    /**
     * Instantiates a new cache time frame dao.
     *
     * @param config the config
     * @param daoSession the dao session
     */
    public CacheTimeFrameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     *
     * @param db the db
     * @param ifNotExists the if not exists
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CACHE_TIME_FRAME' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'LAST' INTEGER," + // 1: last
                "'FIRST' INTEGER," + // 2: first
                "'NEXT_FRAME' INTEGER);"); // 3: nextFrame
    }

    /**
     * Drops the underlying database table.
     *
     * @param db the db
     * @param ifExists the if exists
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CACHE_TIME_FRAME'";
        db.execSQL(sql);
    }

    /**
     * Bind values.
     *
     * @param stmt the stmt
     * @param entity the entity
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, CacheTimeFrame entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date last = entity.getLast();
        if (last != null) {
            stmt.bindLong(2, last.getTime());
        }
 
        java.util.Date first = entity.getFirst();
        if (first != null) {
            stmt.bindLong(3, first.getTime());
        }
 
        Long nextFrame = entity.getNextFrame();
        if (nextFrame != null) {
            stmt.bindLong(4, nextFrame);
        }
    }

    /* (non-Javadoc)
     * @see de.greenrobot.dao.AbstractDao#attachEntity(java.lang.Object)
     */
    @Override
    protected void attachEntity(CacheTimeFrame entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /**
     * Read key.
     *
     * @param cursor the cursor
     * @param offset the offset
     * @return the long
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /**
     * Read entity.
     *
     * @param cursor the cursor
     * @param offset the offset
     * @return the cache time frame
     * @inheritdoc
     */
    @Override
    public CacheTimeFrame readEntity(Cursor cursor, int offset) {
        CacheTimeFrame entity = new CacheTimeFrame( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // last
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // first
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // nextFrame
        );
        return entity;
    }
     
    /**
     * Read entity.
     *
     * @param cursor the cursor
     * @param entity the entity
     * @param offset the offset
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, CacheTimeFrame entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLast(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setFirst(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setNextFrame(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /**
     * Update key after insert.
     *
     * @param entity the entity
     * @param rowId the row id
     * @return the long
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(CacheTimeFrame entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /**
     * Gets the key.
     *
     * @param entity the entity
     * @return the key
     * @inheritdoc
     */
    @Override
    public Long getKey(CacheTimeFrame entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * Checks if is entity updateable.
     *
     * @return true, if is entity updateable
     * @inheritdoc
     */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** The select deep. */
    private String selectDeep;

    /**
     * Gets the select deep.
     *
     * @return the select deep
     */
    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCacheTimeFrameDao().getAllColumns());
            builder.append(" FROM CACHE_TIME_FRAME T");
            builder.append(" LEFT JOIN CACHE_TIME_FRAME T0 ON T.'NEXT_FRAME'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    /**
     * Load current deep.
     *
     * @param cursor the cursor
     * @param lock the lock
     * @return the cache time frame
     */
    protected CacheTimeFrame loadCurrentDeep(Cursor cursor, boolean lock) {
        CacheTimeFrame entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CacheTimeFrame nextTimeFrame = loadCurrentOther(daoSession.getCacheTimeFrameDao(), cursor, offset);
        entity.setNextTimeFrame(nextTimeFrame);

        return entity;    
    }

    /**
     * Load deep.
     *
     * @param key the key
     * @return the cache time frame
     */
    public CacheTimeFrame loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /**
     * Reads all available rows from the given cursor and returns a list of new ImageTO objects.
     *
     * @param cursor the cursor
     * @return the list
     */
    public List<CacheTimeFrame> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CacheTimeFrame> list = new ArrayList<CacheTimeFrame>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    /**
     * Load deep all and close cursor.
     *
     * @param cursor the cursor
     * @return the list
     */
    protected List<CacheTimeFrame> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /**
     * A raw-style query where you can pass any WHERE clause and arguments.
     *
     * @param where the where
     * @param selectionArg the selection arg
     * @return the list
     */
    public List<CacheTimeFrame> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
