package tub.iosp.budcloand.framework.control.database;

import java.util.Map;

import tub.iosp.budcloand.framework.model.BCItem;
import tub.iosp.budcloand.framework.model.BCMetaData;
import tub.iosp.budcloand.framework.model.BCSubscribtion;
import tub.iosp.budcloand.framework.model.CacheTimeFrame;
import tub.iosp.budcloand.framework.model.channelPostsScope;
import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.IdentityScopeType;


// TODO: Auto-generated Javadoc
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * The Class DaoSession.
 *
 * {@inheritDoc}
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    /** The cache time frame dao config. */
    private final DaoConfig cacheTimeFrameDaoConfig;
    
    /** The channel posts scope dao config. */
    private final DaoConfig channelPostsScopeDaoConfig;
    
    /** The b c subscribtion dao config. */
    private final DaoConfig bCSubscribtionDaoConfig;
    
    /** The b c item dao config. */
    private final DaoConfig bCItemDaoConfig;
    
    /** The b c meta data dao config. */
    private final DaoConfig bCMetaDataDaoConfig;

    /** The cache time frame dao. */
    private final CacheTimeFrameDao cacheTimeFrameDao;
    
    /** The channel posts scope dao. */
    private final channelPostsScopeDao channelPostsScopeDao;
    
    /** The b c subscribtion dao. */
    private final BCSubscribtionDao bCSubscribtionDao;
    
    /** The b c item dao. */
    private final BCItemDao bCItemDao;
    
    /** The b c meta data dao. */
    private final BCMetaDataDao bCMetaDataDao;

    /**
     * Instantiates a new dao session.
     *
     * @param db the db
     * @param type the type
     * @param daoConfigMap the dao config map
     */
    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheTimeFrameDaoConfig = daoConfigMap.get(CacheTimeFrameDao.class).clone();
        cacheTimeFrameDaoConfig.initIdentityScope(type);

        channelPostsScopeDaoConfig = daoConfigMap.get(channelPostsScopeDao.class).clone();
        channelPostsScopeDaoConfig.initIdentityScope(type);

        bCSubscribtionDaoConfig = daoConfigMap.get(BCSubscribtionDao.class).clone();
        bCSubscribtionDaoConfig.initIdentityScope(type);

        bCItemDaoConfig = daoConfigMap.get(BCItemDao.class).clone();
        bCItemDaoConfig.initIdentityScope(type);

        bCMetaDataDaoConfig = daoConfigMap.get(BCMetaDataDao.class).clone();
        bCMetaDataDaoConfig.initIdentityScope(type);

        cacheTimeFrameDao = new CacheTimeFrameDao(cacheTimeFrameDaoConfig, this);
        channelPostsScopeDao = new channelPostsScopeDao(channelPostsScopeDaoConfig, this);
        bCSubscribtionDao = new BCSubscribtionDao(bCSubscribtionDaoConfig, this);
        bCItemDao = new BCItemDao(bCItemDaoConfig, this);
        bCMetaDataDao = new BCMetaDataDao(bCMetaDataDaoConfig, this);

        registerDao(CacheTimeFrame.class, cacheTimeFrameDao);
        registerDao(channelPostsScope.class, channelPostsScopeDao);
        registerDao(BCSubscribtion.class, bCSubscribtionDao);
        registerDao(BCItem.class, bCItemDao);
        registerDao(BCMetaData.class, bCMetaDataDao);
    }
    
    /**
     * Clear.
     */
    public void clear() {
        cacheTimeFrameDaoConfig.getIdentityScope().clear();
        channelPostsScopeDaoConfig.getIdentityScope().clear();
        bCSubscribtionDaoConfig.getIdentityScope().clear();
        bCItemDaoConfig.getIdentityScope().clear();
        bCMetaDataDaoConfig.getIdentityScope().clear();
    }

    /**
     * Gets the cache time frame dao.
     *
     * @return the cache time frame dao
     */
    public CacheTimeFrameDao getCacheTimeFrameDao() {
        return cacheTimeFrameDao;
    }

    /**
     * Gets the channel posts scope dao.
     *
     * @return the channel posts scope dao
     */
    public channelPostsScopeDao getChannelPostsScopeDao() {
        return channelPostsScopeDao;
    }

    /**
     * Gets the bC subscribtion dao.
     *
     * @return the bC subscribtion dao
     */
    public BCSubscribtionDao getBCSubscribtionDao() {
        return bCSubscribtionDao;
    }

    /**
     * Gets the bC item dao.
     *
     * @return the bC item dao
     */
    public BCItemDao getBCItemDao() {
        return bCItemDao;
    }

    /**
     * Gets the bC meta data dao.
     *
     * @return the bC meta data dao
     */
    public BCMetaDataDao getBCMetaDataDao() {
        return bCMetaDataDao;
    }

}

