package tub.iosp.budcloand.framework.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.IdentityScopeType;

import tub.iosp.budcloand.framework.database.CacheTimeFrameDao;
import tub.iosp.budcloand.framework.database.channelPostsScopeDao;
import tub.iosp.budcloand.framework.database.BCSubscribtionDao;
import tub.iosp.budcloand.framework.database.BCItemDao;
import tub.iosp.budcloand.framework.database.BCMetaDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CacheTimeFrameDao.createTable(db, ifNotExists);
        channelPostsScopeDao.createTable(db, ifNotExists);
        BCSubscribtionDao.createTable(db, ifNotExists);
        BCItemDao.createTable(db, ifNotExists);
        BCMetaDataDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CacheTimeFrameDao.dropTable(db, ifExists);
        channelPostsScopeDao.dropTable(db, ifExists);
        BCSubscribtionDao.dropTable(db, ifExists);
        BCItemDao.dropTable(db, ifExists);
        BCMetaDataDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CacheTimeFrameDao.class);
        registerDaoClass(channelPostsScopeDao.class);
        registerDaoClass(BCSubscribtionDao.class);
        registerDaoClass(BCItemDao.class);
        registerDaoClass(BCMetaDataDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
